[mypy]
python_executable = d:/smart-attendance/attendance_backend/smart/Scripts/python.exe
ignore_missing_imports = True
follow_imports = silent
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_optional = True
show_column_numbers = True

# Third-party packages without stubs
[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-qrcode.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True
